### ISSUE TITLE
MiniChat par Abdulrahman Elhabboub

### ISSUE THREAD

**Issue by AbedHabboub** [ISSAE/nsy103#11]
Bonjour,

Voici les liens du projet:
version TCP: https://github.com/AbedHabboub/MiniChatTCP.git
version UDP: https://github.com/AbedHabboub/MiniChat.git

Merci,
Abed

**Comment by pascalfares** [comment]
submodule : creation
AbedHabboubTCP et AbedHabboub

Question: pourquoi 2?

**Comment by AbedHabboub** [comment]
Deux implementations sont réalisées l'une en TCP, l'autre en UDP. J'ai séparé les codes.
